### PR TITLE
Add auto-text advance delay option, add Load to main menu, save anywhere toggle fix

### LINKED ISSUE #2207: Toggling save anywhere should enable the save menu without having to close and reopen the menu

### LINKED ISSUE #2209: Add Load option to main menu
Should go straight to the Load screen for the current campaign, still needing to quit to title to switch campaigns.

### LINKED ISSUE #2212: Gameplay option: Auto-text advance delay timer
Add a configurable delay timer for auto-text advance.

### PR DESCRIPTION
**Pull request by warblgarbl**
Auto-text advance delay default is 1 second.

Closes #2207.
Closes #2209.
Closes #2212.

### CODE REVIEW

File: src/main/java/legend/game/Scus94491BpeSegment_8002.java [hunk 1]
```diff
@@ -2250,8 +2252,12 @@ public static void handleTextboxText(final int textboxIndex) {
           textboxText.state_00 = TextboxTextState.SCROLL_TEXT_DOWN_9;
           textboxText.flags_08 |= 0x1;
         } else {
+          if(CONFIG.getConfig(CoreMod.AUTO_TEXT_CONFIG.get()) && autoTextDelayStart == 0) {
+            autoTextDelayStart = System.nanoTime();
+          }
           //LAB_8002686c
-          if(PLATFORM.isActionPressed(INPUT_ACTION_MENU_CONFIRM.get()) || CONFIG.getConfig(CoreMod.AUTO_TEXT_CONFIG.get())) {
+          if(PLATFORM.isActionPressed(INPUT_ACTION_MENU_CONFIRM.get()) || (CONFIG.getConfig(CoreMod.AUTO_TEXT_CONFIG.get()) && System.nanoTime() - autoTextDelayStart >= CONFIG.getConfig(CoreMod.AUTO_TEXT_DELAY_CONFIG.get()) * 0x3B9A_CA00)) {
```
Comment (LordMonoxide) [inline src/main/java/legend/game/Scus94491BpeSegment_8002.java:2259]: This would be much easier to understand in decimal :P

File: src/main/java/legend/game/inventory/screens/MainMenuScreen.java [hunk 2]
```diff
@@ -333,15 +340,59 @@ private void showOptionsScreen() {
       ConfigStorage.saveConfig(CONFIG, ConfigStorageLocation.CAMPAIGN, gameState_800babc8.campaign.path.resolve("campaign_config.dcnf"));
       menuStack.popScreen();
       this.loadingStage = 0;
+      for(int i = 0; i < this.menuButtons.size(); i++) {
+        if(Objects.equals(this.menuButtons.get(i).getText(), "Save")) {
```
Comment (LordMonoxide) [inline src/main/java/legend/game/inventory/screens/MainMenuScreen.java:344]: You can safely do `"Save".equals(...)`

Comment (LordMonoxide) [reply src/main/java/legend/game/inventory/screens/MainMenuScreen.java:344]: Actually, reading and understanding this, it'd be better to keep a reference to the save button when adding it. This menu will get translated and checking for the english button name isn't a good solution.

File: src/main/java/legend/game/inventory/screens/MainMenuScreen.java [hunk 3]
```diff
@@ -333,15 +340,59 @@ private void showOptionsScreen() {
...
+  }
+
   private void showSaveScreen() {
     if(canSave_8011dc88) {
       menuStack.pushScreen(new SaveGameScreen(() -> {
         menuStack.popScreen();
         this.fadeOutArrows();
         this.loadingStage = 0;
+        for(int i = 0; i < this.menuButtons.size(); i++) {
+          if(Objects.equals(this.menuButtons.get(i).getText(), "Load")) {
```
Comment (LordMonoxide) [inline src/main/java/legend/game/inventory/screens/MainMenuScreen.java:391]: Same goes here for disabling the button

File: src/main/java/legend/game/Scus94491BpeSegment_8002.java (hunk 1 above)
Comment (warblgarbl) [reply src/main/java/legend/game/Scus94491BpeSegment_8002.java:2259]: "Hex is better" he says lol

**Review by LordMonoxide — APPROVED** [review]
