### PR TITLE
Error handling on OptionsScreen to handle errors thrown by configs

### LINKED ISSUE #1615: Ensure mod config options only crash the mod container
image

### PR DESCRIPTION
**Pull request by FrancisDionne**
Closes #1615

### CODE REVIEW

File: src/main/java/legend/game/inventory/screens/OptionsScreen.java [hunk 1]
```diff
@@ -73,35 +90,148 @@ public OptionsScreen(final ConfigCollection config, final Set<ConfigStorageLocat
...
     }
 
     return InputPropagation.PROPAGATE;
   }
 
   @Override
   protected void render() {
-    super.render();
-    renderText(I18n.translate("lod_core.ui.options.help_hotkey", "\u0120"), 334, 226, this.fontOptions);
+    try {
```
Comment (LordMonoxide) [inline src/main/java/legend/game/inventory/screens/OptionsScreen.java:151]: Don't need to wrap this one, need to wrap `renderControls` instead

File: src/main/java/legend/game/inventory/screens/ControlHost.java [hunk 2]
```diff
@@ -84,6 +84,10 @@ public Iterator<Control> iterator() {
     return this.controls.iterator();
   }
 
+  protected Control findControlAt(final int index) {
```
Comment (LordMonoxide) [inline src/main/java/legend/game/inventory/screens/ControlHost.java:87]: A better name for this is `getControl` because it's a simple accessor for the controls list, the other one is named `findControlAt` because it's actually searching through the controls for the topmost control at those coordinates

File: src/main/java/legend/game/inventory/screens/OptionsScreen.java [hunk 3]
```diff
@@ -73,35 +90,148 @@ public OptionsScreen(final ConfigCollection config, final Set<ConfigStorageLocat
       });
   }
 
-  @Override
-  public InputPropagation pressedThisFrame(final InputAction inputAction) {
-    if(super.pressedThisFrame(inputAction) == InputPropagation.HANDLED) {
-      return InputPropagation.HANDLED;
+  private Label createErrorLabel(final String log, final Object obj, final boolean setSize) {
+    LOGGER.warn(log, obj);
+    final Label l = new Label("Error");
```
Comment (LordMonoxide) [inline src/main/java/legend/game/inventory/screens/OptionsScreen.java:95]: Anything displayed on the front end needs to go through the translation system

File: src/main/java/legend/game/inventory/screens/OptionsScreen.java [hunk 4]
```diff
@@ -73,35 +90,148 @@ public OptionsScreen(final ConfigCollection config, final Set<ConfigStorageLocat
...
-      this.unload.run();
-      return InputPropagation.HANDLED;
+    return l;
+  }
+
+  private void replaceControlWithErrorLabel(final String log, final Object obj) {
+    final Label row = this.getHighlightedRow();
+    if(row != null) {
+      row.getFontOptions().colour(0.30f, 0.0f, 0.0f).shadowColour(TextColour.LIGHT_BROWN);
+      final Control c = row.findControlAt(0);
```
Comment (LordMonoxide) [inline src/main/java/legend/game/inventory/screens/OptionsScreen.java:111]: Is it possible for a config to add more than one control?

**Review by LordMonoxide — CHANGES_REQUESTED** [review]

File: src/main/java/legend/game/inventory/screens/OptionsScreen.java (hunk 4 above)
Comment (FrancisDionne) [reply src/main/java/legend/game/inventory/screens/OptionsScreen.java]: I made it a loop instead

File: src/main/java/legend/game/inventory/screens/OptionsScreen.java [hunk 5]
```diff
@@ -73,27 +90,56 @@ public OptionsScreen(final ConfigCollection config, final Set<ConfigStorageLocat
       });
   }
 
-  @Override
-  public InputPropagation pressedThisFrame(final InputAction inputAction) {
-    if(super.pressedThisFrame(inputAction) == InputPropagation.HANDLED) {
-      return InputPropagation.HANDLED;
+  private Label createErrorLabel(final String log, final Object obj, final boolean setSize) {
```
Comment (LordMonoxide) [inline src/main/java/legend/game/inventory/screens/OptionsScreen.java:93]: Sorry, missed this last night, change `Object` to `Throwable` here and in the other method so that it uses the right overload in the logger

File: src/main/resources/lod_core/lang/en.lang [hunk 6]
```diff
@@ -21,6 +21,7 @@ lod_core.ui.mods.required=Required mod
 lod_core.ui.mods.error=Crashed: %s
 lod_core.ui.mods.wrong_version=Wrong version: %s
 lod_core.ui.mods.hotkeys=%s Help
+lod_core.ui.mods.error=Error
```
Comment (LordMonoxide) [inline src/main/resources/lod_core/lang/en.lang:24]: Should be `lod_core.ui.options.error`, move down a couple lines to the options UI group

**Review by LordMonoxide — APPROVED** [review]
