### PR TITLE
Fix loading from menu

### LINKED ISSUE #2225: Load from Main Menu: Aglis Psyche Bomb Trial Missing NPCs
Savan and Lulu don't load into the correct position. Same result when just warping to the submap with the debugger. Something particular about how the map is loaded from the title screen.

### PR DESCRIPTION
**Pull request by avionanx**
Got some fields to name later, _800bd7ac, _800bd7b0

### CODE REVIEW

**Comment by avionanx** [comment]
Oops this messed WMAP

**Comment by avionanx** [comment]
Needs to be tested with loading from disc change saves

File: src/main/java/legend/game/inventory/screens/MainMenuScreen.java [hunk 1]
```diff
@@ -357,23 +361,34 @@ private void showLoadScreen() {
...
 
       submapScene_80052c34 = gameState_800babc8.submapScene_a4;
-      submapCut_80052c30 = gameState_800babc8.submapCut_a8;
+      if(gameState_800babc8.isOnWorldMap_4e4) {
+        submapCut_80052c30 = 0;
+      } else {
+        submapCut_80052c30 = gameState_800babc8.submapCut_a8;
+      }
+
+      if(currentEngineState_8004dd04 instanceof final SMap smap && !gameState_800babc8.isOnWorldMap_4e4) {
```
Comment (LordMonoxide) [inline src/main/java/legend/game/inventory/screens/MainMenuScreen.java:379]: Can you explain these changes? The reason the engine state had loadGameFromMenu is so that the engine state gets to decide how to restore itself. What happens when a mod adds its own engine state that can save/load? We can't add another `else if instanceof` here for that

Comment (avionanx) [reply src/main/java/legend/game/inventory/screens/MainMenuScreen.java:379]: Oops, forgot we already had custom engine states. Will re-add and move these

**Review by LordMonoxide — APPROVED** [review]
