### PR TITLE
fix addition sound rc (closes #2218)

### LINKED ISSUE #2218: Additions - Incorrect sound plays
Additions sometimes trigger seemingly random sounds (level up, open chest, etc) rather than the intended sounds.

I have not encountered this myself, but have seen a couple instances when watching streams. These two examples happen to be from people playing nodart runs with a petrified character in the party.

Meru Double Smack from current test: https://www.twitch.tv/umihimeyokai/clip/KathishSneakyRingCoolCat-HcqkTger6OmjhIdB

Lavitz Flower Storm from a much older build: https://www.twitch.tv/dillonwithablankie/clip/AbstruseEagerWheelTBCheesePull-3OsEQ90myeGkLewY

### PR DESCRIPTION
**Pull request by avionanx**

### CODE REVIEW

File: src/main/java/legend/game/Scus94491BpeSegment.java [hunk 1]
```diff
@@ -2397,14 +2388,25 @@ public static void loadEncounterSoundsAndMusic() {
...
     loadedDrgnFiles_800bcf78.updateAndGet(val -> val | 0x8);
 
+    final AtomicInteger remaining = new AtomicInteger(0);
+
     // Player combat sounds for current party composition (example file: 764)
     for(int charSlot = 0; charSlot < 3; charSlot++) {
       final int charIndex = gameState_800babc8.charIds_88[charSlot];
 
       if(charIndex != -1) {
+        remaining.incrementAndGet();
```
Comment (LordMonoxide) [inline src/main/java/legend/game/Scus94491BpeSegment.java:2398]: Set to 3 when constructed, otherwise if the first thread completes before the second one starts then it will decrement to 0 and consider it loaded

File: src/main/java/legend/game/Scus94491BpeSegment.java [hunk 2]
```diff
@@ -2397,14 +2388,25 @@ public static void loadEncounterSoundsAndMusic() {
...
+
         final String name = getCharacterName(charIndex).toLowerCase();
         final int finalCharSlot = charSlot;
-        loadDir("characters/%s/sounds/combat".formatted(name), files -> charSoundEffectsLoaded(files, finalCharSlot));
+        loadDir("characters/%s/sounds/combat".formatted(name), files -> {
+          charSoundEffectsLoaded(files, finalCharSlot);
+          if(remaining.decrementAndGet() == 0){
```
Comment (LordMonoxide) [inline src/main/java/legend/game/Scus94491BpeSegment.java]: Space before brace

Comment (avionanx) [reply src/main/java/legend/game/Scus94491BpeSegment.java]: already did

**Review by LordMonoxide — APPROVED** [review]
