### PR TITLE
Fix battle lighting; fix unknown minor lighting bugs; add shader reloading (closes #1152)

### LINKED ISSUE #1152: Seles battle lighting has a blue tint

### PR DESCRIPTION
**Pull request by LordMonoxide**

### CODE REVIEW

File: src/main/java/legend/core/RenderEngine.java [hunk 1]
```diff
@@ -1333,7 +1349,7 @@ private void storeTransforms(final int modelIndex, final FloatBuffer transforms2
 
       if(this.lightUsed) {
         this.lightDirection.get(modelIndex * 32, lightingBuffer);
-        this.lightColour.get(modelIndex * 32 + 16, lightingBuffer);
+        put3x4(this.lightColour, modelIndex * 32 + 16, lightingBuffer);
```
Comment (LordMonoxide) [inline src/main/java/legend/core/RenderEngine.java:1354]: This is the fix: in std140 layout shader uniforms, mat3's are stored as 3 vec4's with the W component being 0

**Review by Zychronix — APPROVED** [review]
